cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIAUKJCKBKMSAJKAR3P
      secret-key: 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
server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration